services:
  wg-easy:
    image: ghcr.io/wg-easy/wg-easy
    container_name: nas-vpn
    environment:
      # The public IP or DDNS of your Mac
      - WG_HOST=${WG_HOST}
      # The password for the Web UI (port 51821)
      - PASSWORD=${WG_PASSWORD}
      - WG_DEFAULT_ADDRESS=10.8.0.x
      - WG_DEFAULT_DNS=1.1.1.1
      - WG_ALLOWED_IPS=10.8.0.0/24, 0.0.0.0/0
      # Optional: set to true to enable persistent keepalive
      - WG_PERSISTENT_KEEPALIVE=25
    volumes:
      - ./config/wireguard:/etc/wireguard
    ports:
      - "51820:51820/udp" # WireGuard VPN Port
      - "51821:51821/tcp" # Web UI for Admin
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.src_valid_mark=1
    restart: unless-stopped
