logging:
  pattern:
    console: %d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] [%X{traceId}] %-5level %logger{36} - %msg%n
app:
  storage:
    root: /mnt/host_volumes
    cache-dir: /app/cache
  security:
    default-password: admin123

spring:
  application:
    name: backend

  threads:
    virtual:
      enabled: true

  datasource:
    url: jdbc:postgresql://nas-db:5432/nas_db
    username: ${NAS_USER:nas_user}
    password: ${NAS_PASSWORD:default_password_local_development_only}
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      format_sql: true

  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true

jwt:
  secret: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
  expiration: 86400000

security:
  vpn:
    allowed-subnets: 10.8.0.0/24,127.0.0.1/32,172.16.0.0/12,192.168.0.0/16,10.0.0.0/8
